Linux install istructions
janniks/git-ignore pull request #5
Opened 2021-11-19 08:56 UTC by PsykeDady

2021-12-10 08:50 UTC, Uzaaft commented
There is an easier way to do this: `cargo install --path . ` after cloning and entering the repository. 
This will add the CLI to `~/.cargo/bin/`

2021-12-10 12:59 UTC, PsykeDady commented
But you must have `~/.cargo/bin` in your own PATH. 
I can add as another installation method i suppone

2021-12-10 14:13 UTC, janniks requested changes
Awesome, thank you so much for the detailed instructions

2021-12-10 14:13 UTC, janniks commented on README.md
> +From now on, you simply run `git-ignore` to launch the interactive CLI, anytime you want to setup or change a `.gitignore` file.
```suggestion
From now on, you simply run `git ignore` to launch the interactive CLI, anytime you want to setup or change a `.gitignore` file.
```

The cool thing with git is, we can actually run this as `git ignore`. Would love to keep this as is.

2021-12-10 17:36 UTC, Uzaaft commented
> But you must have `~/.cargo/bin` in your own PATH.
> I can add as another installation method i suppone

I think having this as a must is a sensible thing to do, considering the fact that the rust-lang website even mentions this.
Besides, if you were to add it manually, since it is a a user binary, it  should be placed in `/usr/local/binary` and not `/usr/bin`

2021-12-10 23:21 UTC, merged

2021-12-10 23:42 UTC, janniks commented
🚀 Thanks for the input @PsykeDady and @Uzaaft — This was very helpful! I expanded the instructions a bit and think it now covers both cases. 🙏

2021-12-11 00:24 UTC, PsykeDady commented
Thanks to you!